apiVersion: v1
kind: Service
metadata:
  name: movie-parley-lb
spec:
  type: LoadBalancer
  selector:
    app: movie-parley
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-parley-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-parley
  template:
    metadata:
      labels:
        app: movie-parley
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: movie-parley
          image: baddockerhub/movieparley-backend:dummy
          ports:
            - containerPort: 80
              protocol: TCP
