kind: Service
apiVersion: v1
metadata:
  name: movieparley-backend
spec:
  type: LoadBalancer
  selector:
    app: movieparley-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieparley-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieparley-backend
  template:
    metadata:
      labels:
        app: movieparley-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-reg-cred
      containers:
        - name: nginx
          image: baddockerhub/movie-parley:latest
          ports:
            - containerPort: 8080
              protocol: TCP
