apiVersion: v1
kind: Service
metadata:
  name: my-python-app-lb
spec:
  type: LoadBalancer
  selector:
    app: my-python-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: my-python-app
          image: baddockerhub/my-python-app
          ports:
            - containerPort: 80
              protocol: TCP
