apiVersion: v1
kind: Service
metadata:
  name: movieparley-backend-service
spec:
  selector:
    app: movieparley-backend
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieparley-backend-deployment
  labels:
    app: movieparley-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieparley-backend
  template:
    metadata:
      labels:
        app: movieparley-backend
    spec:
      containers:
        - name: movieparley-backend
          image: movieparley-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080