version: '3.6'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: movie_parley
    ports:
      - 27017:27017

networks:
  default:
    name: movie-parley-network